# **Numpy**

**(Numarical python)**

- used for working with arrays. 

- In python we have list that serve tha purpuse of arrays, but they are also to process.

- Numpy is incredible library to perform mathematical and statistical operations due to its fast and memory efficient as it is optimize to work with latest cpu archiectures.

- Numpy aims to provide an array object that is up to 50x faster than traditional python list. So processes can access and manupulate them very efficiently.

In [4]:
import numpy as np

# Numpy Arrays

**0D ARRAY**

In [5]:
a=45
print(a)
print(type(a))

45
<class 'int'>


In [6]:
a=45
arr_0 = np.array(a)
print(arr_0)
print(type(arr_0))

45
<class 'numpy.ndarray'>


In [7]:
arr_0.ndim

0

In [7]:
arr_0.shape

()

**1D ARRAY**

In [8]:
a=[1,2,3]

arr_1=np.array(a)
print(arr_1)

[1 2 3]


In [9]:
arr_1.ndim

1

In [10]:
arr_1.shape

(3,)

**2D ARRAY**

In [11]:
a=[[1,2,4]]
arr_2=np.array(a)
print(arr_2)

[[1 2 4]]


In [12]:

arr_2.ndim

2

In [13]:
arr_2.shape

(1, 3)

# Functions for creating 1D array

**Arrange**

- Arrange is an array-value version of the built-in python range function
- **Syntax**:np.arrange(start,end,step)

In [14]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
a = np.arange(10,50,5)
print(a)

[10 15 20 25 30 35 40 45]


**Linespace**

- Return evenly spaced number over a specified interval.
- **Syntax**:np.linespace(start,end,num_of_samples)

In [16]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [17]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

**Zero**

- Genarate arrays of zeros
- **Syntax**: np.zero(shape)

In [18]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**ones**

- Genarate arrays of zeros
- **Syntax**: np.zero(shape)

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Random.randint**

- Return random integer from start (inclusve) to end (exclusive)
- **Syntax**: np.random(start,end,num_of_samples)

In [20]:
np.random.randint(1,10,2)

array([9, 4])

In [21]:
np.random.randint(1,10,5)

array([2, 6, 7, 3, 7])

In [35]:
#findind the index of the maximum value
a = np.array([1,2,3,4,5,6])
max_index=np.argmax(a)
print(max_index)

5


**Accessing elements/Extracting the values**

1.Accessing a single value through indexing

2.Accessing a multiple values based on slicing

3.Accessing a multiple values based on indexing

4.Accessing a multiple values based on condition

In [10]:
a = np.arange(10,101,15) 
print(a)


[ 10  25  40  55  70  85 100]


**1.Accessing a single value through indexing**

In [23]:
a = np.arange(10,51,10) 
print(a)


[10 20 30 40 50]


In [24]:
#positive indexing
a[1]

20

In [25]:
#negitive indexing
a[-1]

50

2. Accessing a multiple values based on slicing

In [26]:
a[1:5:2]


array([20, 40])

In [27]:
a[-1:-4:-1]

array([50, 40, 30])

3. Accessing a multiple values based on indexing


- **Syntax**: array[list of index number]

In [44]:
a[[0,3,2,1,2]]

array([10, 25, 20, 15, 20])

In [45]:
a.ndim

1

4. Accessing a multiple values based on condition(Mask indexing or fancy indexing)

- **Syntax**: array[list of index]
- 
--first, it will check the condition the item which satisfies the condition (means which item gives True for the condition). that item will be selected 

In [27]:
a=np.array([45,46,47])
a[a%2==0]

array([46])

# Modify the values in numpy

- Add a single va;lue in array
- **Syntax**: np.append(array,value)

In [28]:
a = np.array([45,46,47])
a1 = np.append(a,48)
print(a1)

[45 46 47 48]


- Add a multiply value in a 1D array

In [29]:
a = np.array([1,2,3])
a2 = np.append(a,[4,5,6])
print(a2)

[1 2 3 4 5 6]


- Replacing the single value in a 1D array

In [30]:
a[0] = 120
print(a)

[120   2   3]


- Replacing a multiple values with a single value in a array

In [31]:
a[[1,2]] = 12
a

array([120,  12,  12])

- Replacing a multiple values with a multiple value in a array

In [32]:
a[[1,2]] = [20,25]
a

array([120,  20,  25])

**Delete a single value in a array**
- **Syntax** : np.delete(aray,indexnumber)

In [33]:
a3 = np.delete(a,1)
print(a3)

[120  25]


**Delete a multiple value in a array**
- **Syntax** : np.delete(Array,[multiple index number])

In [34]:
# Deleting the multiple values
a4 = np.delete(a,[1,2])
print(a4)

[120]


**Copy array**

In [35]:
a = np.array([1,2,3])
b = a.copy()
b[0] =100
print(a)
print(b)


[1 2 3]
[100   2   3]


**Sorting an array**

In [36]:
a = np.array([4,8,5,4,6,7,9])
b = np.sort(a)
print(b)

[4 4 5 6 7 8 9]


# **operations**
- **Arthimetic Operations**

In [37]:
a = np.array([1,2,3,4])
b = a+1
print(b)

[2 3 4 5]


In [38]:
c = a+0
print(c)

[1 2 3 4]


In [39]:
d = a**2
print(d)

[ 1  4  9 16]


In [40]:
print(a+b)


[3 5 7 9]


In [41]:
print(a-b)


[-1 -1 -1 -1]


In [42]:
print(a*b)


[ 2  6 12 20]


**Comparision operations**

In [43]:
a == c

array([ True,  True,  True,  True])

In [44]:
c >= a

array([ True,  True,  True,  True])

In [45]:
np.array_equal(a,b)

False

In [46]:
np.array_equal(a,c)

True

**Mathematical operations**

In [47]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [48]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [49]:
import warnings
warnings.simplefilter("ignore")

# **2D Numpy Array**

In [51]:
b = np.array([[0,1,2,3],[2,3,4,5]])
print(b)

[[0 1 2 3]
 [2 3 4 5]]


In [52]:
b.ndim

2

In [53]:
b.shape

(2, 4)

In [55]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [59]:
# identity matrix 
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
a=np.eye(10,10)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
a.ndim

2

In [61]:
#Diagional matrix 
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
np.diag([1,2,3,4,5,6,7,8,9])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [70]:
#Diagional matrix 
a=np.array([[1,2,3],[3,2,5],[1,2,3]])
np.diag(a)

array([1, 2, 3])

In [71]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


**Indexing of 2D array**

In [74]:
#all coloums by default 
a[0]

array([10, 20, 30])

In [75]:
a[2]

array([70, 80, 90])

In [76]:
a[2,2]

90

In [78]:
a[1:3]

array([[40, 50, 60],
       [70, 80, 90]])

In [82]:
a[:3]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [83]:
#assinding value in 2d arraay
a[1]=[20,25,30]
a

array([[10, 20, 30],
       [20, 25, 30],
       [70, 80, 90]])

In [84]:
a[0,2]=500
a

array([[ 10,  20, 500],
       [ 20,  25,  30],
       [ 70,  80,  90]])

**Flattening**: Converting 2D array to 1D

In [10]:
import numpy as np

In [11]:
a= np.array([[0,1,2], [3,4,5]])
print(a)

b=a.ravel()
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


**Reshape array**

In [12]:
a=np.arange(6)
print(a)
print(a.shape)

[0 1 2 3 4 5]
(6,)


In [16]:
a1=a.reshape(2,3)
print(a1)


[[0 1 2]
 [3 4 5]]


In [18]:
a1=a.reshape(3,2)
a1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
a1=a.reshape(6,1)
a

array([0, 1, 2, 3, 4, 5])

In [23]:
a=np.array([[0,1,2],[10,2,3]])
print(a)
print(a.shape)


[[ 0  1  2]
 [10  2  3]]
(2, 3)


In [24]:
print(a.reshape(3,2))

[[ 0  1]
 [ 2 10]
 [ 2  3]]


In [25]:
c=a .T
print(c)

[[ 0 10]
 [ 1  2]
 [ 2  3]]


# Sort

In [27]:
#sorting along an axis: axis=1--> row and axis=0-->coloum
a= np.array([[1,22,31],[4,25,16],[7,28,19]])

b=np.sort(a,axis=0)         #formula for sorting(axis=0)           
                           #this is for ROW
b

array([[ 1, 22, 16],
       [ 4, 25, 19],
       [ 7, 28, 31]])

In [28]:
a= np.array([[1,22,31],[4,25,16],[7,28,19]])

b=np.sort(a,axis=1)      #formula for sorting(axis=1)
                        #this is for COLOUM
b                            

array([[ 1, 22, 31],
       [ 4, 16, 25],
       [ 7, 19, 28]])

In [32]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[11,22],[55,77],[11,10]])
#adding a and b
print(a+b)

[[12 24]
 [58 81]
 [16 16]]


In [35]:
a=np.array([[11,22],[55,77],[11,10]])
b=np.array([[1,2],[3,4],[5,6]])
#substrating a and b
print(a-b)

[[10 20]
 [52 73]
 [ 6  4]]


In [38]:
a=np.array([[11,22],[55,77],[11,10]])
b=np.array([[1,2],[3,4],[5,6]])
#mutiply a and b
print(a*b)

[[ 11  44]
 [165 308]
 [ 55  60]]


In [40]:
a=np.array([[11,22],[55,77],[11,10]])
b=np.array([[1,2],[3,4],[5,6]])
#division  a and b
print(a/b)

[[11.         11.        ]
 [18.33333333 19.25      ]
 [ 2.2         1.66666667]]


In [49]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#matrix multiplication
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [50]:
np.concatenate((a,b),axis=0)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
#vertical stack
np.vstack((a,b))            ##equal to np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
np.concatenate((a,b),axis=1)


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [53]:
#horizantal stack
np.hstack((a,b))          #equal to np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [30]:
import numpy as np

In [31]:
#dot product
a=np.array([1,2,3])
b=np.array([4,5,6])             #dot product formula (result=np.dot(a,b)
result=np.dot(a,b)
print(result)

32


In [32]:
#dot product 
a=np.array([1,2])
b=np.array([4,6])             #dot product 
dot_product=sum(a*b for a, b in zip (a, b))
print(dot_product)

16


In [2]:
import numpy as np
a = np.arange(10,100,5)
print(a)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [33]:
import numpy as np


In [34]:
np.random.randint(1,10,3)

array([6, 7, 1])

In [35]:
np.linspace(10,100,3)

array([ 10.,  55., 100.])

In [36]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [37]:
np.zeros((10,15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])